spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;MODE=MariaDB;DATABASE_TO_LOWER=TRUE
    username: sa
    password:
  sql:
    init:
      mode: never
  jpa:
    hibernate:
      ddl-auto: create